//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.ToDoRestAPIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ToDoRestAPIService.IToDoListRestAPIService")]
    public interface IToDoListRestAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoListRestAPIService/GetData", ReplyAction="http://tempuri.org/IToDoListRestAPIService/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoListRestAPIService/GetData", ReplyAction="http://tempuri.org/IToDoListRestAPIService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoListRestAPIService/GetLists", ReplyAction="http://tempuri.org/IToDoListRestAPIService/GetListsResponse")]
        WcfTodoListService.DataModel.TodoList[] GetLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoListRestAPIService/GetLists", ReplyAction="http://tempuri.org/IToDoListRestAPIService/GetListsResponse")]
        System.Threading.Tasks.Task<WcfTodoListService.DataModel.TodoList[]> GetListsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoListRestAPIService/GetList", ReplyAction="http://tempuri.org/IToDoListRestAPIService/GetListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfTodoListService.DataModel.RESTAPIExceptionData), Action="http://tempuri.org/IToDoListRestAPIService/GetListRESTAPIExceptionDataFault", Name="RESTAPIExceptionData", Namespace="http://schemas.datacontract.org/2004/07/WcfTodoListService.DataModel")]
        WcfTodoListService.DataModel.TodoList GetList(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoListRestAPIService/GetList", ReplyAction="http://tempuri.org/IToDoListRestAPIService/GetListResponse")]
        System.Threading.Tasks.Task<WcfTodoListService.DataModel.TodoList> GetListAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoListRestAPIService/AddNewList", ReplyAction="http://tempuri.org/IToDoListRestAPIService/AddNewListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfTodoListService.DataModel.RESTAPIExceptionData), Action="http://tempuri.org/IToDoListRestAPIService/AddNewListRESTAPIExceptionDataFault", Name="RESTAPIExceptionData", Namespace="http://schemas.datacontract.org/2004/07/WcfTodoListService.DataModel")]
        string AddNewList(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoListRestAPIService/AddNewList", ReplyAction="http://tempuri.org/IToDoListRestAPIService/AddNewListResponse")]
        System.Threading.Tasks.Task<string> AddNewListAsync(System.IO.Stream data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IToDoListRestAPIServiceChannel : UnitTests.ToDoRestAPIService.IToDoListRestAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ToDoListRestAPIServiceClient : System.ServiceModel.ClientBase<UnitTests.ToDoRestAPIService.IToDoListRestAPIService>, UnitTests.ToDoRestAPIService.IToDoListRestAPIService {
        
        public ToDoListRestAPIServiceClient() {
        }
        
        public ToDoListRestAPIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ToDoListRestAPIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoListRestAPIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoListRestAPIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WcfTodoListService.DataModel.TodoList[] GetLists() {
            return base.Channel.GetLists();
        }
        
        public System.Threading.Tasks.Task<WcfTodoListService.DataModel.TodoList[]> GetListsAsync() {
            return base.Channel.GetListsAsync();
        }
        
        public WcfTodoListService.DataModel.TodoList GetList(string id) {
            return base.Channel.GetList(id);
        }
        
        public System.Threading.Tasks.Task<WcfTodoListService.DataModel.TodoList> GetListAsync(string id) {
            return base.Channel.GetListAsync(id);
        }
        
        public string AddNewList(System.IO.Stream data) {
            return base.Channel.AddNewList(data);
        }
        
        public System.Threading.Tasks.Task<string> AddNewListAsync(System.IO.Stream data) {
            return base.Channel.AddNewListAsync(data);
        }
    }
}
